TaskWeb/Controllers/SqlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskWeb.Aplicacao;
using TaskWeb.Dominio;

namespace TaskWeb.Controllers
{
    public class SqlController : Controller
    {
        // GET: Sql
        public ActionResult Index()
        {
            var cad = new AplicacaoSql();
            var listar = cad.ListarTodos();


            return View(listar);
        }

        public ActionResult Cadastrar()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(CadastroSql sql)
        {
            if (ModelState.IsValid)
            {
                var appSql = new AplicacaoSql();
                appSql.Inserir(sql);
                return RedirectToAction("Index");
            }
            return View(sql);
        } 
    }
}

TaskWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
</head>
<body>
    <div class="slidebar">
        <h2>MENU</h2>
        <ul>
            <li><a @Html.ActionLink("Painel Geral", "Geral", "Home", new {}, new {})</a></li>
            <li><a @Html.ActionLink("Configuracao", "Index", "Sql", new {}, new {})</a></li>
        </ul>
    </div>

    <div class="conteudo">
        <img src="~/Imagens/menu.png" class="menu-bar" />
        @RenderBody()
    </div>

    <script src="~/Scripts/Abrir.js"></script>
    @section Scripts {
        @Scripts.Render("~/bundles/jquery")
    }
</body>
</html>